recipe/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from . import views
from django.urls import path

app_name = 'recipe'

urlpatterns = [path('add-recipe', views.RecipeFormView.as_view(),
               name='add-recipe'), path('recipe-list',
               views.recipe_list, name='recipe-list'),
               path('recipe-details/<int:pk>', views.recipe_details,
               name='recipe-details'), path('recipe-detail-list',
               views.recipe_detail_list, name='recipe-detail-list'),
               path('recipe-download/<int:pk>', views.generate_pdf,
               name='recipe-download'), path('404-error', views.error_page,
               name='404-error'), path('rating', views.rating, name='rating'),
               path('comments', views.add_comment, name='comments'),
               path('user-profile', views.view_profile, name='user-profile'),
               path('edit-profile', views.edit_profile, name='edit-profile'),
               path('media-files', views.show_media_files, name='media-files'),
               # path('demo', views.demo, name='demo')
               ]

recipe_hub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.views.generic.base import TemplateView
from registration import views

urlpatterns = [path('admin/', admin.site.urls), path('',
               views.index, name='index'), path('registration/',
               include('registration.urls')), path('recipe/',
               include('recipe.urls'))] + static(
                   settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from . import views
from django.urls import path

app_name = 'registration'

urlpatterns = [path('', views.index, name='index'), path('register',
               views.UserFormView.as_view(), name='register'),
               path('login', views.LoginFormView.as_view(),
               name='user-login'), path('logout', views.logout_view,
               name='logout'), path('home', views.home, name='home'),
               path('about-us', views.about_us, name='about-us'),
               path('contact-us', views.contact_us, name='contact-us'),
               path('search', views.search, name='search')]

recipe/models.py
from django.db import models

# Create your models here.

recipe/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from registration.models import User, Recipe, Image, Rating
from django import forms


class RecipeForm(forms.ModelForm):

    name = forms.CharField(max_length=50,
                           widget=forms.TextInput(attrs={
                               'class': 'form-control'}), label='Recipe Name')
    incredient = forms.CharField(max_length=1500,
                                 widget=forms.Textarea(attrs={
                               'class': 'form-control'}),
                                 label='Incredients')
    recipe = forms.CharField(max_length=1500, widget=forms.Textarea(attrs={
                               'class': 'form-control'}),
                             label='Preparation')
    video = forms.FileField(max_length=500, widget=forms.FileInput(attrs={
                               'class': 'form-control'}),
                            label='Video')
    image = forms.FileField(max_length=500,
                            widget=forms.FileInput(attrs={'multiple': '',
                                'class': 'form-control'}),
                            label='Image')

    class Meta:

        model = Recipe
        fields = ['name', 'incredient', 'recipe', 'video']


class EditUserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'profile_pic']

recipe/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import RecipeForm, EditUserForm
from django.views.decorators.cache import cache_control
from django.contrib.auth.decorators import login_required
from el_pagination.decorators import page_template
from django.views.generic import View
from registration.models import Recipe, Image, Rating, Comment, User
from django.db.models import Avg
from io import BytesIO
from django.http import HttpResponse, JsonResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
import random
import os
from django.template.defaultfilters import slugify


class RecipeFormView(View):

    form_class = RecipeForm
    template_name = 'recipe/recipe_form.html'

    @cache_control(no_cache=True, must_revalidate=True, no_store=True)
    def get(self, request):
        form = self.form_class(None)
        username = request.user
        return render(request, self.template_name, {'form': form,
                      'username': username})

    @cache_control(no_cache=True, must_revalidate=True, no_store=True)
    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():

            new_recipe = form.save(commit=False)
            new_recipe.user = request.user
            name = form.cleaned_data['name']
            incredient = form.cleaned_data['incredient']
            recipe = form.cleaned_data['recipe']
            video = request.FILES.get('video')
            new_recipe.save()
            for pics in request.FILES.getlist('image'):
                recipe_image = Image(recipe=new_recipe, image=pics)
                recipe_image.save()
        return render(request, self.template_name, {'form': form})


@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def recipe_list(request):
    template_name = 'recipe/recipe_list.html'
    username = request.user
    recipe = Recipe.objects.all()
    word = request.GET.get('word', False)
    if word:
        recipe = Recipe.objects.filter(name__icontains=word)
    context = {'username': username,
                  'recipe': recipe}
    return render(request, template_name, context)


@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def recipe_details(request, pk):
    template_name = 'recipe/recipe_details.html'
    username = request.user
    recipe = Recipe.objects.filter(pk=pk)
    rating = Rating.objects.filter(recipe=pk).aggregate(Avg('value'))
    if recipe:
        image = Image.objects.filter(recipe=pk)
        rating_count = Rating.objects.filter(recipe=pk).count()
        if rating_count == 0:
            rating_text = 'Rate the recipe 1st.'
        else:
            rating_text = 'Average Rating :' + str(rating['value__avg'])
        context = {'username': username, 'recipe': recipe,
                   'image': image, 'avg_rating': rating_text}
    else:
        return redirect('recipe:404-error')
    return render(request, template_name, context)


@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def recipe_detail_list(request, context):
    return render(request, 'recipe/recipe_details.html', context)


def render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode('UTF-8')), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(),
                            content_type='application/pdf')
    return None


@login_required
def generate_pdf(request, pk):
    template = 'recipe/recipe_pdf.html'
    current_recipe = Recipe.objects.filter(pk=pk)
    if current_recipe:
        recipe_pic = Image.objects.filter(recipe=pk)
        no = random.randint(10000, 99999)
        for name in current_recipe:
            slug = 'Recipe-Hub-' + name.name + '-' + str(no)
        context = {'recipe': current_recipe, 'pics': recipe_pic}

        pdf = render_to_pdf(template, context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = slugify(slug)
            content = "inline; filename='%s'" % filename
            response['Content-Disposition'] = content
        # return render(request, template, context)
    else:
        return redirect('recipe:404-error')
    return response


@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def rating(request):
    user = request.user
    recipe = request.POST.get('recipe')
    recipe_obj = Recipe.objects.get(pk=recipe)
    rating = request.POST.get('rating')
    all_recipes = Rating.objects.filter(user=user, recipe=recipe_obj)
    rating_list = all_recipes.count()
    if rating_list == 0:
        new_rating = Rating(user=user, recipe=recipe_obj, value=rating)
        new_rating.save()
    else:
        new_rating = Rating.objects.filter(user=user, recipe=recipe_obj)
        new_rating.update(value=rating)
    current_recipe = Rating.objects.filter(recipe=recipe_obj)
    avg_rating = current_recipe.aggregate(Avg('value'))
    return JsonResponse({'message': 'Your rating successfully added.',
                         'avg_rating': int(avg_rating['value__avg'])})


@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def add_comment(request):
    user = request.user.pk
    recipe = request.POST.get('recipe')
    comment = request.POST.get('comment')
    if comment:
        current_recipe = Recipe.objects.get(pk=recipe)
        current_user = User.objects.get(pk=user)
        new_comment = Comment.objects.create(
            recipe=current_recipe, user=current_user, comment=comment)
        new_comment.save()
        comment = '<p><b>' + str(new_comment.user) + '</b> : ' + new_comment.comment + '</p>'
        return JsonResponse({'comment': comment})
    else:
        msg = "Please enter a comment"
        return JsonResponse({'status': msg})


@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def view_profile(request):
    user = request.user.pk
    current_user = User.objects.get(pk=user)
    user_recipe = Recipe.objects.filter(user=user)
    return render(request, 'recipe/profile.html',
                          {'username': request.user,
                           'current_user': current_user,
                           'user_recipe': user_recipe
                           })


@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def edit_profile(request):
    form_class = EditUserForm
    if request.method == 'POST':
        form = form_class(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            new_user = form.save()
            return redirect('recipe:user-profile')
    else:
        form = form_class(instance=request.user)
    return render(request, 'recipe/edit_profile.html',
                  {'form': form, 'username': request.user})


def show_media_files(request):
    videos = Recipe.objects.filter(user=request.user)
    for video in videos:
        images = Image.objects.filter(recipe=video)
    return render(request, 'recipe/media.html',
                  {'images': images, 'videos': videos})


def error_page(request):
    return render(request, 'recipe/error404.html')


# def demo(request):
#     slider = list()
#     count = list()
#     i = 0
#     path = '/home/djr5/recipe_hub/media/recipe_pics'
#     for x in os.listdir(path):
#         if os.path.isfile(os.path.join(path, x)):
#             slider.append(x)
#             count.append(i)
#             i = i + 1
#     return render(request, 'recipe/comments.html', {'demo': slider, 'count': count})

recipe/templates/recipe/comments.html
{% extends 'base.html' %}
{% block content %}
	<div class="container">
	  <h2>Carousel Example</h2>
	  <div id="myCarousel" class="carousel slide" data-ride="carousel">
	    <!-- Indicators -->
	    <ol class="carousel-indicators">
	    {% for i in count %}
	    	{% if i == 0 %}
	    		<li data-target="#myCarousel" data-slide-to="{{i}}" class="active"></li>
	    	{% else %}
	    		<li data-target="#myCarousel" data-slide-to="{{i}}"></li>
	    	{% endif %}
	    {% endfor %}
	    </ol>
	    <!-- Wrapper for slides -->

	    <div class="carousel-inner">
	    	<div class="item active">
	        <img src="/media/recipe_pics/{{i}}" class="img-responsive" alt="Los Angeles" style="width:800px; height:500px;">
	        <div class="carousel-caption">
	          <h3>Recipe Hub</h3>
	          <p>where foodies meet together!</p>
	        </div>
	      </div>
	    {% for i in demo %}
	      <div class="item">
	        <img src="/media/recipe_pics/{{i}}" class="img-responsive" alt="Los Angeles" style="width:800px; height:500px;">
	        <div class="carousel-caption">
	          <h3>Recipe Hub</h3>
	          <p>where foodies meet together!</p>
	        </div>
	      </div>
	     {% endfor %}
	    </div>

	    <!-- Left and right controls -->
	    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
	      <span class="glyphicon glyphicon-chevron-left"></span>
	      <span class="sr-only">Previous</span>
	    </a>
	    <a class="right carousel-control" href="#myCarousel" data-slide="next">
	      <span class="glyphicon glyphicon-chevron-right"></span>
	      <span class="sr-only">Next</span>
	    </a>
	  </div>
    </div>
{% endblock %}

recipe/templates/recipe/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% load image_tags %}
{% block content %}
	<nav class="navbar navbar-inverse">
   		<div class="container" style="margin: auto;">
	       	<div class="navbar-header" >
	       		<img src="{{ user.profile_pic.url}}" class="img-circle" alt="profile-image" height="50px" width="80px">
	            <label style="color: black;" >Hello {{username}}</label>
	       	</div>
		       <ul class="nav navbar-nav">
		           <li><a href="{% url 'recipe:recipe-list' %}" style="margin-left: 10px;">Home</a></li>
		           <li class="active"><a href="{% url 'recipe:user-profile' %}">Profile</a></li>
		           <li><a href="{% url 'recipe:add-recipe' %}">Add Recipes</a></li>
		           <li><a href="{% url 'recipe:media-files' %}">Images & Videos</a></li>
		           <li><a href="{% url 'registration:logout' %}">Logout</a></li>
		       </ul>
  		</div>
	</nav>
	{% block title %}<h1 align="center">{{username}}'s Profile</h1>{% endblock %}
	<div align="center">
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.as_p}}
			<a href="{% url 'recipe:user-profile' %}">
                <button class="btn btn-success" type="submit">Update Profile</button>
            </a>
		</form>
	</div>
	
{% endblock %}

recipe/templates/recipe/error404.html
<!DOCTYPE html>
<html>
<head>
	<title>Recipe Hub</title>
</head>
<body>
	<img src="/media/404error.jpg" width="100%">
</body>
</html>

recipe/templates/recipe/media.html
{% extends 'base.html' %}
{% load static %}
{% load image_tags %}
{% block content %}
	<nav class="navbar navbar-inverse">
   		<div class="container" style="margin: auto;">
	       	<div class="navbar-header" >
	       		<img src="{{ user.profile_pic.url}}" class="img-circle" alt="profile-image" height="50px" width="80px">
	            <label style="color: black;" >Hello {{username}}</label>
	       	</div>
		       <ul class="nav navbar-nav">
		           <li><a href="{% url 'recipe:recipe-list' %}" style="margin-left: 10px;">Home</a></li>
		           <li><a href="{% url 'recipe:user-profile' %}">Profile</a></li>
		           <li><a href="{% url 'recipe:add-recipe' %}">Add Recipes</a></li>
		           <li class="active"><a href="{% url 'recipe:media-files' %}">Images & Videos</a></li>
		           <li><a href="{% url 'registration:logout' %}">Logout</a></li>
		       </ul>
  		</div>
	</nav>
	<div class="container" align="center">
		<div>
			<h3>Your Recipe images</h3>
			{% for image in images %}
				<img class="media-image" src="{{image.image.url}}" alt="recipe-image">
			{% endfor %}
		</div>
		<div>
			<h3>Your Recipe Videos</h3>
			{% for video in videos %}
				<video class="media-video" controls="">
					<source src="{{video.video.url}}">
				</video>
			{% endfor %}
		</div>
	</div>
{% endblock %}

recipe/templates/recipe/profile.html
{% extends 'base.html' %}
{% load static %}
{% load image_tags %}
{% block content %}
	<nav class="navbar navbar-inverse">
   		<div class="container" style="margin: auto;">
	       	<div class="navbar-header" >
	       		<img src="{{ user.profile_pic.url}}" class="img-circle" alt="profile-image" height="50px" width="80px">
	            <label style="color: black;" >Hello {{username}}</label>
	       	</div>
		       <ul class="nav navbar-nav">
		           <li><a href="{% url 'recipe:recipe-list' %}" style="margin-left: 10px;">Home</a></li>
		           <li class="active"><a href="{% url 'recipe:user-profile' %}">Profile</a></li>
		           <li><a href="{% url 'recipe:add-recipe' %}">Add Recipes</a></li>
		           <li><a href="{% url 'recipe:media-files' %}">Images & Videos</a></li>
		           <li><a href="{% url 'registration:logout' %}">Logout</a></li>
		       </ul>
  		</div>
	</nav>
	{% block title %}<h1 align="center">{{username}}'s Profile</h1>{% endblock %}
	<div class="container">
		<div class="col-md-6">
			<div>
				<img src="{{ current_user.profile_pic.url}}" class="img-rounded" alt="profile-pic">
			</div>
		</div>
		<div class="col-md-6">
			<div>
				<p><label>Username : {{current_user.username}}</label></p>
				<p><label>Full name : {{current_user.first_name}} {{current_user.last_name}}</label></p>
				<p><label>Email : {{current_user.email}}</label></p>
				<a href="{% url 'recipe:edit-profile' %}">
                	<button class="btn btn-warning" type="submit">Edit Profile</button>
            	</a>
			</div>
			<div id="recipe-list-in-profile">
				<h3><u>Your Recipes</u></h3>
				{% for recipe in user_recipe %}
					<p><a href="/recipe/recipe-details/{{recipe.pk}}">{{recipe.name}}</a></p>
				{% endfor %}
			</div>
			
		</div>

	</div>
{% endblock %}

recipe/templates/recipe/recipe_details.html
{% extends 'base.html' %}
{% load static %}
{% load el_pagination_tags %}
{% load image_tags %}
{{ block.super }}
{% block content %}
	<nav class="navbar navbar-inverse">
   		<div class="container" style="margin: auto;">
	       	<div class="navbar-header" >
	       		<img src="{{ user.profile_pic.url}}" class="img-circle" alt="profile-image" height="50px" width="80px">
	            <label style="color: black;" >Hello {{username}}</label>
	       	</div>
		       <ul class="nav navbar-nav">
		           <li class="active"><a href="{% url 'recipe:recipe-list' %}" style="margin-left: 10px;">Home</a></li>
		           <li><a href="{% url 'recipe:user-profile' %}">Profile</a></li>
		           <li><a href="{% url 'recipe:add-recipe' %}">Add Recipes</a></li>
		           <li><a href="{% url 'recipe:media-files' %}">Images & Videos</a></li>
		           <li><a href="{% url 'registration:logout' %}">Logout</a></li>
		       </ul>
  		</div>
	</nav>
	{% for recipe in recipe %}
	<div class="container">
		<div class="modal fade" id="myModal" role="dialog">
		    <div class="modal-dialog">
		    
		      <!-- Modal content-->
		      <div class="modal-content">
		        <div class="modal-header">
		          <h4 class="modal-title">Recipe Hub</h4>
		        </div>
		        <div class="modal-body">
		          <div class="panel panel-success" >
				      <div class="panel-heading" id="success_text"></div>
				  </div>
		        </div>
		      </div>
		      
		    </div>
		 </div>
		<div align="center">
			<hr>
			<h3>
				{{recipe.name}}
			</h3>
			{% for pic in image %}
				<img src="{{pic.image.url}}" class="img-rounded" width="400" height="200" alt="picture">
			{% endfor %}
			<hr>
		</div>
		<div align="center">
			<video controls="" width="900">
				<source src="{{recipe.video.url}}">
			</video>
		</div>
		<hr>
		<div align="left" class="col-md-8 recipe-text">
			<span>
				<h4> Incredients </h4>
				<p>
					{{recipe.incredient}}
				</p>	
			</span>
			<span>
				<h4>How to cook {{recipe.name}}
				</h4>
				<p>
					{{recipe.recipe}}
				</p>	
			</span>
		</div>
		<div align="center" class=" col-md-2">
		 <a href='/recipe/recipe-download/{{recipe.pk}}'><button class="btn btn-danger">Download Recipe</button></a>  
		</div>
		<div class='comment-box col-md-4'>
			{% include "recipe/star.html" %}
			<div id="comment-list">
				<input type="text" name="comment" class="form-control comment-textbox" id="{{ recipe.pk }}" placeholder="Comment Here">
				<button class="btn btn-success" onclick="recipeComment(this.name)" name="{{ recipe.pk }}">Comment</button>
			</div>
			<div id="commentdisplay">
				{% recipe_comment recipe.pk as comments %}
					{% for comment in comments%}
						<p><b>{{comment.user}}</b> : {{comment.comment}}</p>
					{% endfor %}
			</div>
		</div>
	</div>
	{% endfor %}
	<hr>
	<script src="{% static 'js/el-pagination.js'%}"></script>
	<script >$('#commentdisplay').endlessPaginate({paginateOnScroll:true});</script>
	<script type="text/javascript">  
    function MyRating(temp){
      var radio1=$('input[type="radio"]:checked').val();
          $.ajax({
              url : "/recipe/rating",
              type : "POST",
              data : {
                'rating' : radio1,
                'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val(),
                'recipe':temp
            },
              success : function(data) {
                $("#success_text").html(data.message);
                $("#avg_rating").html('Average Rating :'+data.avg_rating);
            	$("#myModal").modal('show');
            setTimeout(function() {
              $('#myModal').modal('hide');
            }, 1000);
              }
          });
          return false;
    } 
    function recipeComment(recipe_id){
        var comment = document.getElementById(recipe_id).value;
        $.ajax({
            url:'/recipe/comments',
            method:'POST',
            data:{'recipe': recipe_id, 'comment': comment,
            'csrfmiddlewaretoken': '{{ csrf_token }}'},
            success: function(response)
            {   
	    		if(response.status){
	            	alert("Please add Comment before submitting.")
	            }
	            else{
	            	$('#commentdisplay').prepend(response.comment);
	            	$('.comment-textbox').empty()
	            }
	            

            }
            
	                
        });
    } 
  </script>
{% endblock %}

recipe/templates/recipe/recipe_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 
	<nav class="navbar navbar-inverse">
   		<div class="container" style="margin: auto;">
	       	<div class="navbar-header" >
	       		<img src="{{ user.profile_pic.url}}" class="img-circle" alt="profile-image" height="50px" width="80px">
	            <label style="color: black;" >Hello {{username}}</label>
	       	</div>
		       <ul class="nav navbar-nav">
		           <li><a href="{% url 'recipe:recipe-list' %}"style="margin-left: 10px;">Home</a></li>
		           <li><a href="{% url 'recipe:user-profile' %}">Profile</a></li>
		           <li class="active"><a href="{% url 'recipe:add-recipe' %}">Add Recipes</a></li>
		           <li><a href="{% url 'recipe:media-files' %}">Images & Videos</a></li>
		           <li><a href="{% url 'registration:logout' %}">Logout</a></li>
		       </ul>
  		</div>
	</nav>
	{% block title %}<h1 align="center">Add Recipe</h1>{% endblock %}
    <div>
        <form method="post" enctype="multipart/form-data" class="col-md-4">
            {% csrf_token %} {{ form.as_p}}
            <button type="submit" class="btn btn-info">Add</button>
        </form>
    </div> 
{% endblock %}

recipe/templates/recipe/recipe_list.html
{% extends 'base.html' %}
{% load static %}
{% load image_tags %}
{% block content %} 
	<nav class="navbar navbar-inverse">
   		<div class="container" style="margin: auto;">
	       	<div class="navbar-header" >
	       		<img src="{{ user.profile_pic.url}}" class="img-circle"  alt="profile-image" height="50px" width="80px">
	            <label style="color: black;" >Hello {{username}}</label>
	       	</div>
		       <ul class="nav navbar-nav">
		           <li class="active"><a href="{% url 'recipe:recipe-list' %}" style="margin-left: 10px;">Home</a></li>
		           <li><a href="{% url 'recipe:user-profile' %}">Profile</a></li>
		           <li><a href="{% url 'recipe:add-recipe' %}">Add Recipes</a></li>
		           <li><a href="#">Images & Videos</a></li>
		           <li><a href="{% url 'registration:logout' %}">Logout</a></li>
		       </ul>
	        <div align="right">
	       		<form method="get" action="#">
	       			{% csrf_token %}
			       	<input type="text" name="word" id="word" >
		           	<input type="submit" value="Search" >
		       </form>
	       </div>
  		</div>
	</nav>
	<div id="recipes" class="col-md-12" align="center">
        {% for rp in recipe %}
        	<hr>
	        {% recipe_images rp.pk as pics %}
        	{% for imgs in pics %}
        		<img src="{{ imgs }}" class="img-rounded" alt="picture" width="400" height="200">
			{% endfor %}
            <p><b>Recipe Name : </b>{{ rp.name }}</p>
            <p><b>Posted By : </b>{{ rp.user }}</p>
            <p>
        		<a href="/recipe/recipe-details/{{ rp.pk }}"><button type="submit" class="btn btn-warning" name="{{ rp.pk }}">View More
        		</button></a>
            </p>
            <hr>
        {% endfor %}
    </div> 
    
{% endblock %}

recipe/templates/recipe/recipe_pdf.html
<!DOCTYPE html>
<html>
<head>
	<title>Recipe Hub</title>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="http://127.0.0.1:8000/static/css/star.css">
</head>
<body>
	<div>
		{% for recipe in recipe %}
			<h2 align="center">{{ recipe.name }}</h2>
			<hr>
			<div align="center">
				{% for img in pics %}
					<img src="http://127.0.0.1:8000{{img.image.url}}" class="img-circle" alt="recipe-image" width="350" height="200">
				{% endfor %}
			</div>
			<hr>
			<h4>Incredients</h4>
			<p class="pdf_text">
				{{ recipe.incredient }}
			</p>
			<h4>How to cook {{recipe.name}}</h4>
			<p class="pdf_text">
				{{ recipe.recipe }}
			</p>
			<hr>
			<strong>Posted By : {{recipe.user}}</strong>
		{% endfor %}
	</div>
</body>
</html>